package hu.am.electronicvote.vote.exception;

public enum ErrorCode {
    UNEXPECTED_ERROR,
    DOUBLED_VOTE,
    INVALID_USER,
    MULTIPLE_ANSWER,
    NOT_LOGGED_IN_USER,
    NOT_LOGGED_IN_USER_BECAUSE_OF_USER_LOCK_FOR_SHORT_TIME,
    NOT_LOGGED_IN_USER_BECAUSE_OF_USER_LOCK_FOR_LONG_TIME,
    NOT_LOGGED_IN_USER_BECAUSE_OF_USER_LOCK_FOR_PERSONAL_AUTHENTICATION
}
